CREATE TABLE Adobe (
    `Request_Summary` VARCHAR(110) CHARACTER SET utf8,
    `Product_Name` VARCHAR(44) CHARACTER SET utf8
);
INSERT INTO Adobe VALUES ('REQ #7030514 - NonITMGMT unable to open any pdf','Adobe Acrobat 9.0 Standard');
INSERT INTO Adobe VALUES ('REQ #7028218 - NonITMGMT PDF files','Adobe Reader');
INSERT INTO Adobe VALUES ('Install Adobe Creative Suite 4 Web Premium Version:  OS: W7','Adobe Creative Suite 4 Web Premium');
INSERT INTO Adobe VALUES ('Install Adobe Photoshop Version:  OS: W7','Adobe Photoshop');
INSERT INTO Adobe VALUES ('REQ #7024814 - NonITMGMT language issue','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #7024143 - NonITMGMT Unable to open PDF Files','Adobe Reader');
INSERT INTO Adobe VALUES ('Install AdobDreamweaver Version:  OS: W7','Adobe Dreamweaver');
INSERT INTO Adobe VALUES ('Install Adobe Creative Suite 3 Production Premium Version:  OS: W7','Adobe Creative Suite 3 Production Premium');
INSERT INTO Adobe VALUES ('Remove Adobe Reader Version:  OS: W7','Adobe Reader');
INSERT INTO Adobe VALUES ('Install Adobe Acrobat 7.0 Professional Version:  OS: W7','Adobe Acrobat 7.0 Professional');
INSERT INTO Adobe VALUES ('NonITMGMT Request to install SVG.','Adobe SVG Viewer');
INSERT INTO Adobe VALUES ('REQ #7001099 - NonITMGMT pdf files fail to open','Adobe Reader');
INSERT INTO Adobe VALUES ('NonITMGMT Adobe reader issue','Adobe Acrobat 6.0 Professional');
INSERT INTO Adobe VALUES ('Install  Version:  OS: W7','Adobe Digital Editions 3.0');
INSERT INTO Adobe VALUES ('Upgrade Adobe Reader Version:  OS: W7','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #7002970 - NonITMGMT Unbale to open PDF files','Adobe Acrobat 6.0 Professional');
INSERT INTO Adobe VALUES ('REQ #7002970 - NonITMGMT Unbale to open PDF files','Adobe Acrobat 6.0 Professional');
INSERT INTO Adobe VALUES ('REQ #7008771 -','Adobe After Effects');
INSERT INTO Adobe VALUES ('REQ #7007939 - NonITMGMT Could not open any of the PDF file','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #7008081 - NonITMGMT User called in as he was unable to open any .PDF files','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #7008081 - NonITMGMT User called in as he was unable to open any .PDF files','Adobe Reader');
INSERT INTO Adobe VALUES ('Install  Version:  OS: W7','Adobe Acrobat XI Pro');
INSERT INTO Adobe VALUES ('Install  Version:  OS: W7','adobe flash player 1.1.1');
INSERT INTO Adobe VALUES ('Niehl S1  (mneufel1,18553) REQ #6992461 - NonITMGMT unable to install Adobe Acrobat 11 Pro','Adobe Acrobat 9.0 Pro');
INSERT INTO Adobe VALUES ('NonITMGMT Adobe issue','Adobe Acrobat 6.0 Professional');
INSERT INTO Adobe VALUES ('Install Adobe Acrobat 6.0 Professional Version:  OS:','Adobe Acrobat 6.0 Professional');
INSERT INTO Adobe VALUES ('Remove  Version:  OS: W7','adobe desgin suit');
INSERT INTO Adobe VALUES ('REQ #7004046 - NonITMGMT User could not open Pdf in Adobe by default','Adobe Acrobat 9.0 Standard');
INSERT INTO Adobe VALUES ('NonITMGMT Unable to open pdf files','Adobe Reader');
INSERT INTO Adobe VALUES ('NonITMGMT PDF','Adobe Reader');
INSERT INTO Adobe VALUES ('Install Adobe  production premium Suite Version:  OS: W7','Adobe  production premium Suite');
INSERT INTO Adobe VALUES ('REQ #6974595 - NonITMGMT Need to reinstall','Adobe Acrobat 9.0 Pro');
INSERT INTO Adobe VALUES ('REQ #6957046 - NonITMGMT Cannot open .dxf file','Adobe Illustrator');
INSERT INTO Adobe VALUES ('Install Adobe Photoshop Version:  OS: W7','Adobe Photoshop');
INSERT INTO Adobe VALUES ('NonITMGMT Unable to open PDF Files','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6987347 - NonITMGMT not able to open pdf','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6987347 - NonITMGMT not able to open pdf','Adobe Reader');
INSERT INTO Adobe VALUES ('Install Adobe SVG Viewer Version:  OS: W7','Adobe SVG Viewer');
INSERT INTO Adobe VALUES ('Install Adobe SVG Viewer Version:  OS: W7','Adobe SVG Viewer');
INSERT INTO Adobe VALUES ('Remove Adobe Reader XI (11.0.06) MUI - SELF INSTALL Version:  OS: W7','Adobe Reader XI (11.0.06) MUI - SELF INSTALL');
INSERT INTO Adobe VALUES ('REQ #6991409 - NonITMGMT PDF issue','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6988569 - NonITMGMT Adobe Pro XI has installed 4 times and still doesn''t work','Adobe Acrobat 9.0 Pro');
INSERT INTO Adobe VALUES ('REQ #6990043 - NonITMGMT Cannot to run the application','Adobe SVG Viewer');
INSERT INTO Adobe VALUES ('Remove Adobe Reader Version:  OS: W7','Adobe Reader');
INSERT INTO Adobe VALUES ('Install Adober Acrobat  XI Pro Version:  OS: W7','Adober Acrobat  XI Pro');
INSERT INTO Adobe VALUES ('REQ #6987811 - NonITMGMT impossible to open files','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6986157 - NonITMGMT Adobe is not opening','Adobe Acrobat 6.0 Professional');
INSERT INTO Adobe VALUES ('Remove Adobe Photoshop Version:  OS: W7','Adobe Photoshop');
INSERT INTO Adobe VALUES ('Install Adobe SVG Viewer 3.0 Version:  OS: W7','Adobe SVG Viewer 3.0');
INSERT INTO Adobe VALUES ('Install Adobe Creative Suite 4 Design Premium Version:  OS: W7','Adobe Creative Suite 4 Design Premium');
INSERT INTO Adobe VALUES ('REQ #6980639 - NonITMGMT Unable to open the PDF files','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6964476 - NonITMGMT Not able to open PDF Files','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6980539 - NonITMGMT user is not able to open any of the pdf files in the computer','Adobe Reader');
INSERT INTO Adobe VALUES ('Install Adobe Reader Version:  OS: W7','Adobe Reader');
INSERT INTO Adobe VALUES ('Upgrade Adobe Flash Version:  OS:','Adobe Flash');
INSERT INTO Adobe VALUES ('Install Adobe Photoshop Version:  OS: W7','Adobe Photoshop');
INSERT INTO Adobe VALUES ('REQ #6971404 - NonITMGMT acrobat failed to connect to a dde server','Adobe Acrobat 9.0 Standard');
INSERT INTO Adobe VALUES ('REQ #6971404 - NonITMGMT acrobat failed to connect to a dde server','Adobe Acrobat 9.0 Standard');
INSERT INTO Adobe VALUES ('Install Adobe SVG Viewer Version:  OS: W7','Adobe SVG Viewer');
INSERT INTO Adobe VALUES ('REQ #6961668 - NonITMGMT cant print pdf files','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6961668 - NonITMGMT cant print pdf files','Adobe Reader');
INSERT INTO Adobe VALUES ('NonITMGMT Unable to open Adobe reader','Adobe Reader');
INSERT INTO Adobe VALUES ('Install Adobe Acrobat 9.0 Pro Version:  OS: W7','Adobe Acrobat 9.0 Pro');
INSERT INTO Adobe VALUES ('REQ #6965875 - NonITMGMT Unable to print form a particular PDF file.','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6965875 - NonITMGMT Unable to print form a particular PDF file.','Adobe Reader');
INSERT INTO Adobe VALUES ('Install Adobe Photoshop Version:  OS: Mac OS X','Adobe Photoshop');
INSERT INTO Adobe VALUES ('Install Adobe Design Suite Version:  OS: W7','Adobe Design Suite');
INSERT INTO Adobe VALUES ('NonITMGMT asked user to download from self service','Adobe Acrobat 9.0 Standard');
INSERT INTO Adobe VALUES ('Request-Manual install of Photoshop Premiere v9','Adobe Photoshop CS5');
INSERT INTO Adobe VALUES ('REQ #6963766 - NonITMGMT user called in for Adobe Production Premium (VIDEO) Suite','Adobe Premiere Elements');
INSERT INTO Adobe VALUES ('REQ #6963766 - NonITMGMT user called in for Adobe Production Premium (VIDEO) Suite','Adobe Premiere Elements');
INSERT INTO Adobe VALUES ('Install Adobe Reader Version:  OS: W7','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6964832 - NonITMGMT unable to open pdf','Adobe Reader');
INSERT INTO Adobe VALUES ('Install Adobe Photoshop Version:  OS: W7','Adobe Photoshop');
INSERT INTO Adobe VALUES ('Request-Manual install of Adobe Premier v10','Adobe Premiere Elements');
INSERT INTO Adobe VALUES ('Install Adobe SVG Viewer Version:  OS: W7','Adobe SVG Viewer');
INSERT INTO Adobe VALUES ('REQ #6958542 - NonITMGMT Unable to view Arial font content in PDF files','Adobe Acrobat 6.0 Standard');
INSERT INTO Adobe VALUES ('REQ #6961999 - NonITMGMT Previous 7 zip files have been changed to abode files','Adobe Acrobat 6.0 Standard');
INSERT INTO Adobe VALUES ('REQ #6953209 - NonITMGMT not allowing to select and open links','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6961576 - NonITMGMT Unable to view wiring diagrams on Professional Service Tech','Adobe SVG Viewer');
INSERT INTO Adobe VALUES ('REQ #6926420 - NonITMGMT MSVCR110.DLL missing upon Photoshop installation','Adobe Photoshop');
INSERT INTO Adobe VALUES ('REQ #6926420 - NonITMGMT MSVCR110.DLL missing upon Photoshop installation','Adobe Photoshop');
INSERT INTO Adobe VALUES ('REQ #6930126 - NonITMGMT not working','Adobe Photoshop');
INSERT INTO Adobe VALUES ('REQ #6950427 - PC Bldg:5036 Hardware','Adobe Photoshop CS5');
INSERT INTO Adobe VALUES ('REQ #6959818 - NonITMGMT apply for Adobe Software license','Adobe Acrobat 9.0 Standard');
INSERT INTO Adobe VALUES ('REQ #6943364 - NonITMGMT Cannot able to open PDF Files','Adobe Acrobat 9.0 Pro');
INSERT INTO Adobe VALUES ('REQ #6954664 - NonITMGMT issue with the pdf','Adobe Acrobat 9.0 Standard');
INSERT INTO Adobe VALUES ('REQ #6954664 - NonITMGMT issue with the pdf','Adobe Acrobat 9.0 Standard');
INSERT INTO Adobe VALUES ('Install  Version:  OS: W7','adobe digital editions');
INSERT INTO Adobe VALUES ('REQ #6911834 - NonITMGMT Unable to open encrypted PDF files. error - Save failed.','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6911834 - NonITMGMT Unable to open encrypted PDF files. error - Save failed.','Adobe Reader');
INSERT INTO Adobe VALUES ('Install Adobe Reader Version:  OS: W7','Adobe Reader');
INSERT INTO Adobe VALUES ('Install Adobe Acrobat Professional 11 - SELF INSTALL Version:  OS: Microsoft Windows 7 Enterprise SP1 (64-bit)','Adobe Acrobat Professional 11 - SELF INSTALL');
INSERT INTO Adobe VALUES ('Upgrade Adobe Illustrator Version:  OS: W7','Adobe Illustrator');
INSERT INTO Adobe VALUES ('Install Adobe Illustrator Version:  OS: W7','Adobe Illustrator');
INSERT INTO Adobe VALUES ('REQ #6943788 - NonITMGMT pdf files are not opening','Adobe Reader');
INSERT INTO Adobe VALUES ('Install  Version:  OS: W7','Adobe Flash Player');
INSERT INTO Adobe VALUES ('Install Adobe Acrobat 8.0 Professional Version:  OS: W7','Adobe Acrobat 8.0 Professional');
INSERT INTO Adobe VALUES ('Install Adobe Reader Version:  OS: WINDOWS','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6949987 - NonITMGMT pdf file issue','Adobe Acrobat 7.0 Professional');
INSERT INTO Adobe VALUES ('REQ #6949307 - NonITMGMT unable to open pdf files','Adobe Reader');
INSERT INTO Adobe VALUES ('Install Adobe Acrobat 9.0 Pro Version:  OS: W7','Adobe Acrobat 9.0 Pro');
INSERT INTO Adobe VALUES ('Install Adobe Flash Player Version:  OS: W7','Adobe Flash Player');
INSERT INTO Adobe VALUES ('REQ #6937434 - NonITMGMT User is unable to open any adobe file','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6938293 - NonITMGMT User is unable to open PDF','Adobe Acrobat 9.0 Pro Extended');
INSERT INTO Adobe VALUES ('REQ #6938293 - NonITMGMT User is unable to open PDF','Adobe Acrobat 9.0 Pro Extended');
INSERT INTO Adobe VALUES ('Install  Version:  OS: W7','ADOBE design suite 2014');
INSERT INTO Adobe VALUES ('Install Adobe Photoshop Version:  OS: W7','Adobe Photoshop');
INSERT INTO Adobe VALUES ('REQ #6930080 - NonITMGMT Dosent work','Adobe Creative Suite 4 Web Standard');
INSERT INTO Adobe VALUES ('Install Adobe Reader Version:  OS: W7','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6856463 - NonITMGMT Unable to open Indesign','Adobe InDesign');
INSERT INTO Adobe VALUES ('REQ #6856463 - NonITMGMT Unable to open Indesign','Adobe InDesign');
INSERT INTO Adobe VALUES ('Install Adobe Illustrator Version:  OS: W7','Adobe Illustrator');
INSERT INTO Adobe VALUES ('Install Adobe SVG Viewer Version:  OS: W7','Adobe SVG Viewer');
INSERT INTO Adobe VALUES ('Remove Adobe Content Viewer Version:  OS: W7','Adobe Acrobat Distiller DC');
INSERT INTO Adobe VALUES ('Remove Adobe Content Viewer Version:  OS: W7','Adobe Acrobat DC');
INSERT INTO Adobe VALUES ('Install Adobe writer Version:  OS: W7','Adobe writer');
INSERT INTO Adobe VALUES ('Install Adobe Photoshop Version:  OS: W7','Adobe Photoshop');
INSERT INTO Adobe VALUES ('REQ #6922645 - NonITMGMT I need SVG viewer installed to I can use service manuals online.','Adobe SVG Viewer');
INSERT INTO Adobe VALUES ('Install Adobe Reader Version:  OS: W7','Adobe Reader');
INSERT INTO Adobe VALUES ('Install Adobe Acrobat 9.0 Standard Version:  OS: W7','Adobe Acrobat 9.0 Standard');
INSERT INTO Adobe VALUES ('REQ #6922195 - NonITMGMT when asked to print, file wants to auto save on desktop','Adobe Reader');
INSERT INTO Adobe VALUES ('Install Adobe Acrobat 9.0 Pro Version:  OS: W7','Adobe Acrobat 9.0 Pro');
INSERT INTO Adobe VALUES ('REQ #6931067 - NonITMGMT Adober reader issue','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6930469 - NonITMGMT user''s adobe can''t work normally','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6930469 - NonITMGMT user''s adobe can''t work normally','Adobe Reader');
INSERT INTO Adobe VALUES ('NonITMGMT Adobe flash Player','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6930496 - NonITMGMT user is not able to open the pdf using the adobe reader.','Adobe Reader');
INSERT INTO Adobe VALUES ('Upgrade  Version:  OS: W7','Adobe Reader 8');
INSERT INTO Adobe VALUES ('Install Adobe SVG View 3.0 Version:  OS: W7','Adobe SVG View 3.0');
INSERT INTO Adobe VALUES ('Install  Version:  OS: W7','Adobe Report Builder');
INSERT INTO Adobe VALUES ('NonITMGMT User wants to get the purchase license','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6927111 - NonITMGMT language to be resetted','Adobe Acrobat 9.0 Standard');
INSERT INTO Adobe VALUES ('Install Adobe flash player Version:  OS: W7','Adobe flash player');
INSERT INTO Adobe VALUES ('REQ #6924806 - NonITMGMT user is not able to open any acrobat server. ( acrobat X1)','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6924806 - NonITMGMT user is not able to open any acrobat server. ( acrobat X1)','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6912861 - NonITMGMT user is not able to open any pdf documents today','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6912861 - NonITMGMT user is not able to open any pdf documents today','Adobe Reader');
INSERT INTO Adobe VALUES ('Install Adobe Reader Version:  OS: W7','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6922357 - NonITMGMT Unable to print the pdf files from the printer','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6920442 - NonITMGMT unable to connect to server','Adobe Acrobat 9.0 Standard');
INSERT INTO Adobe VALUES ('REQ #6902595 - NonITMGMT Can''t open pdf files properly','Adobe Reader');
INSERT INTO Adobe VALUES ('Remove Adobe Content Viewer Version:  OS: W7','Adobe Reader XI');
INSERT INTO Adobe VALUES ('Remove Adobe Content Viewer Version:  OS: W7','Adobe Premiere Pro CC 2015');
INSERT INTO Adobe VALUES ('Remove Adobe Content Viewer Version:  OS: W7','Adobe Photoshop CC 2015');
INSERT INTO Adobe VALUES ('Remove Adobe Content Viewer Version:  OS: W7','Adobe Media Encoder CC 2015');
INSERT INTO Adobe VALUES ('Remove Adobe Content Viewer Version:  OS: W7','Adobe Lightroom');
INSERT INTO Adobe VALUES ('Remove Adobe Content Viewer Version:  OS: W7','Adobe Creative Cloud');
INSERT INTO Adobe VALUES ('Remove Adobe Content Viewer Version:  OS: W7','Adobe Content Viewer');
INSERT INTO Adobe VALUES ('Install Adobe Illustrator Version:  OS: W7','Adobe Illustrator');
INSERT INTO Adobe VALUES ('Install Adobe Illustrator,Adobe Photoshop Version:  OS: Mac OS X 11 El Captian','Adobe Illustrator Adobe Photoshop');
INSERT INTO Adobe VALUES ('REQ #6909693 - PC Bldg:5275 Hardware','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6909693 - PC Bldg:5275 Hardware','Adobe Reader');
INSERT INTO Adobe VALUES ('Upgrade Adobe Design Suite CC 2014 - SELF INSTALL Version:  OS: W7','Adobe Design Suite CC 2014 - SELF INSTALL');
INSERT INTO Adobe VALUES ('REQ #6901027 - NonITMGMT Unable to open pdf files','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6901027 - NonITMGMT Unable to open pdf files','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6902081 - NonITMGMT User called in as he was unable to open any .PDF document','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6902081 - NonITMGMT User called in as he was unable to open any .PDF document','Adobe Reader');
INSERT INTO Adobe VALUES ('REQ #6912278 - NonITMGMT Adobe is not working','Adobe Acrobat 6.0 Professional');
INSERT INTO Adobe VALUES ('REQ #6912772 - NonITMGMT Adobe reader issue','Adobe Acrobat 6.0 Professional');
INSERT INTO Adobe VALUES ('REQ #6912599 - NonITMGMT Unable to open PDF','Adobe Acrobat 6.0 Professional');
INSERT INTO Adobe VALUES ('Install Adobe Illustrator Version:  OS: W7','Adobe Illustrator');
INSERT INTO Adobe VALUES ('REQ #6912335 - NonITMGMT  PDF file issue','Adobe Acrobat 6.0 Professional');
INSERT INTO Adobe VALUES ('REQ #6912287 - NonITMGMT Adobe file not opening','Adobe Acrobat 6.0 Professional');
 
